---
global:
  scrape_interval:     1s
  evaluation_interval: 1s
  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'monitor'

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
  - 'rules/node.rules'
#  - 'rules/ceph.rules'

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's Prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: 'ceph.monitor'
#    relabel_configs:
#      - source_labels: ['__address__']
#        regex: '(.*):(.*)'
#        replacement: '${1}'
#        target_label: 'ip'
#    file_sd_configs:
#      - files:
#          - '/etc/prometheus/ceph-monitor.yml'
#        refresh_interval: '1m'
#  - job_name: 'ceph.osd'
#    relabel_configs:
#      - source_labels: ['__address__']
#        regex: '(.*):(.*)'
#        replacement: '${1}'
#        target_label: 'ip'
#    file_sd_configs:
#      - files:
#          - '/etc/prometheus/ceph-osd.yml'
#        refresh_interval: '1m'
#  - job_name: 'syreo.dev.node'
#    metrics_path: '/node'
#    relabel_configs:
#      - source_labels: ['__address__']
#        regex: '(.*):(.*)'
#        replacement: '${1}'
#        target_label: 'ip'
#        extra_labels:
#          env: 'dev'
#    syreo_etcd_configs:
#      - etcd_server: '100.81.155.140:2379'
#        scrape_port: 9129
#        refresh_interval: '30s'
#        extra_labels:
#          env: 'dev'

